### ISSUE TITLE
Will this allow sending Cross-Domain messages?

### ISSUE THREAD

**Issue by jcubic** [GoogleChrome/related-website-sets#159]
In one of the recent version of Chrome new feature was added storage partitioning, that don't allow cross-domian communication on not related domains (it only works for subdomains).

Found this repo in [Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API) article on MDN. Link from a new article [Saying goodbye to third-party cookies in 2024](https://developer.mozilla.org/en-US/blog/goodbye-third-party-cookies/)

Will this API allow sending Cross Domain messages (with localStorage storage event or Broadcast channel)?

Also, it's not clear how to submit the set. Should I create a PR for this repo and add a JSON file? If yes then it's not clear where to add those JSON files.

I need this for my Open Source project that stopped working in Chrome for not related domains https://github.com/jcubic/sysend.js/issues/54

**Comment by johannhof** [comment]
RWS integrates with the Storage Access API so the improvements being made as part of https://github.com/privacycg/storage-access/issues/102 will benefit developers using RWS as well, there's no relaxation of cross-site storage / communication APIs from RWS otherwise.

> Also, it's not clear how to submit the set. Should I create a PR for this repo and add a JSON file? If yes then it's not clear where to add those JSON files.

The full steps are at https://github.com/GoogleChrome/related-website-sets/blob/main/Getting-Started.md, you should edit the [main related_website_sets.JSON file](https://github.com/GoogleChrome/related-website-sets/blob/main/related_website_sets.JSON) in your PR.

**Comment by krgovind** [comment]
@jcubic Note that we are currently running an Origin Trial between Chrome 120-124 if you'd like to test out the use of Storage Access API (SAA) to re-gain access to cross-site communication via localStorage or Broadcast Channel; please see details [here](https://developers.google.com/privacy-sandbox/blog/saa-non-cookie-storage). If the sites in question are within the same RWS, your SAA invocation will be auto-granted in Chrome.

cc @arichiv

**Comment by jcubic** [comment]
@krgovind I already did a month ago.

**Comment by krgovind** [comment]
> @krgovind I already did a month ago.

Ah, indeed. I missed the fact that you had provided feedback on the [relevant repo](https://github.com/arichiv/saa-non-cookie-storage). Thank you!
