### ISSUE TITLE
What to do about .global TLD

### ISSUE THREAD

**Issue by hc1idam** [GoogleChrome/related-website-sets#178]
We have a .global tld that points back to our .com tld. In looking at the guidance for how to handle ccTLD's it states that the ccTLD should be referenced in the ccTLD subsection of the well-known-sites.json. 

In looking at the list of supported ccTLD, .global is not listed, so we are unsure how this should work with a .global domain. Any guidance you can provide on handling .global TLD entries would be appreciated. 

Example of how we think the JSON should be structured per our understanding:

{
      "primary": "https://hc1.com/",
      "serviceSites": [
        "https://hc1cas.com/",
        "https://hc1cas.global/"

      ],
    "rationaleBySite": {
      "https://hc1cas.com/": "hc1 Insights Lab platform authentication service for US.",
      "https://hc1cas.global/": "hc1 Insights Lab platform authentication service for UK region"
    },
      "ccTLDs": {
        "https://hc1.com/": [
          "https://hc1.global/"
        ]
      }
    }

**Comment by sjledoux** [comment]
Hello @hc1idam,

Since `.global` is not listed as a country code TLD in [IANA's database](https://www.iana.org/domains/root/db), the checks wouldn't allow for `https://hc1.global` to be included as a country code alias in the ccTLDs field. If you would still like to include `https://hc1.global` in your Related Website Set, you could instead add an "associatedSites" field to your set with `https://hc1.global` as a member, and additionally include a rationale for the site as well.
