### ISSUE TITLE
PR merge release

### ISSUE THREAD

**Issue by hc1idam** [GoogleChrome/related-website-sets#180]
We have an approved and merged PR

https://github.com/GoogleChrome/related-website-sets/pull/151

We would like to understand the process for when that will be released.

We have an approved PR that was merged last Tuesday (12 Dec 2023).  When will it be available in the general chrome release?

**Comment by hc1idam** [comment]
@cfredric  so how do we test to ensure things are working and stable after the PR is approved and merged in? I would rather not have to wait for a customer to call to tell us that they are unable to get to the application.

**Comment by cfredric** [comment]
@hc1idam you can use `document.requestStorageAccessFor(origin)` and/or `document.requestStorageAccess()` to test that your sites work correctly once your RWS has rolled out to Chrome clients.

You can collect metrics on your sites to see how many of your users are using Chrome, and of them, how many can call `document.requestStorageAccessFor(origin)` and get it to resolve. The ratio of those two numbers is the proportion of Chrome clients that have received your RWS update (and have since restarted Chrome).

If you're debugging locally on a single Chrome client, you can view `chrome://system` to see what RWSes your Chrome client knows about. (This isn't yet available on Chrome Stable; it will be part of the [Chrome 120](https://chromiumdash.appspot.com/commit/84e1377e23d42fcd7ba4c7d431a237e86f4ae368) release.) This can help you determine whether `document.requestStorageAccessFor(origin)` is failing because the Chrome client doesn't know about your RWS, or if it's failing due to some other reason.
