### ISSUE TITLE
Can't push my branch to origin

### ISSUE THREAD

**Issue by frusso-expandi** [GoogleChrome/related-website-sets#354]
I added my set to the file and served it on /.well-known/related-website-set.json of every platform in the object. I'm able to fetch the remote repository and do every normal git interaction, but when i try to push I get this message.

<img width="500" alt="image" src="https://github.com/GoogleChrome/related-website-sets/assets/166724073/1381947c-102e-4315-a899-6d59fac5966c">

What could be the problem? I even signed the CLA

**Comment by cfredric** [comment]
Hi @frusso-expandi,

It's hard to know exactly what's going on without knowing the output of `git status` and `git remote -v`. But my guess is that you're trying to push to a branch on the GoogleChrome/related-website-sets repository, which you don't have permission to do since you're not a maintainer of the repository.

Instead, you should create a "fork" of this repository, make changes in your fork, and then push those changes to GitHub (still on your fork, they're just publicly visible once they leave your computer). Then, GitHub will allow you to create a pull request on the parent repository (this one). Please see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request for more details on this.

**Comment by cfredric** [comment]
I see that you've now opened #355; closing this as completed.
