### ISSUE TITLE
Seeing errors when running check_sites.py locally

### ISSUE THREAD

**Issue by siddhash1** [GoogleChrome/related-website-sets#95]
I'm seeing errors when running the check_sites script locally:
![image](https://github.com/GoogleChrome/related-website-sets/assets/103609322/166a6f88-9874-4a19-b401-451124165d5e)

Are all of these expected?

**Comment by siddhash1** [comment]
Thanks for the workaround. Is there an expected timeline by which we expect existing sites in the sets to migrate to the new "Related Website Sets" well-known endpoints? Also, this one in particular does not seem related to the RWS change:

> The provided service site is not an eTLD+1: https://www.asadcdn.com

**Comment by sjledoux** [comment]
I do not believe we have a specific timeline for when these sites will migrate, but certainly if they plan to make any changes to their sets they will have to migrate all members to the RWS endpoint if they want to pass the checks. Additionally we just created [a PR to add the workaround](https://github.com/GoogleChrome/related-website-sets/pull/96) I described earlier to the "Getting Started Guide", so hopefully we can avoid some of the confusion in the future!


> Also, this one in particular does not seem related to the RWS change
That failure is related to [a separate PR](https://github.com/GoogleChrome/related-website-sets/pull/53) that fixed an issue in how we check the eTLD+1s. Since the submission predated the fix and clearly isn't malicious (the `www` subdomain is not the case we were concerned about), we are treating it similarly to the RWS cases where there isn't a specific timeline on fixing the compliancy of the set.

**Comment by sjledoux** [comment]
Closing this issue out now as [a recent PR](https://github.com/GoogleChrome/related-website-sets/pull/162) provides a much easier workaround to avoid seeing these errors when running the tests locally. Please read [the updated instructions for local testing](https://github.com/GoogleChrome/related-website-sets/blob/main/Getting-Started.md#step-4-testing-your-rws-locally) to see how to run the tests with the new workaround.
